server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: saml-test
  datasource:
    url: jdbc:mysql://localhost:3306/io_saml?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: thingsmatrix@8
    initialization-mode: always
  jpa:
    database: mysql
    database-platform: com.vdenotaris.spring.boot.security.saml.web.config.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
logging:
  file.max-size: 1024MB
  level:
    com.vdenotaris.spring.boot.security.saml: DEBUG
    org.opensaml: DEBUG
    org.springframework.security.saml: trace
    org.springframework.security: debug
  register-shutdown-hook: false
  pattern:
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} [%file : %line] - %msg%n'
  file:
    name: /applogs/backend/${spring.application.name}.log
zhe:
  hostname: 91924d1188c2.ngrok.io



